const Discord = require('discord.js');
const MrFOG1 = new Discord.Client();
const MrFOG2 = new Discord.Client();
const MrFOG3 = new Discord.Client();
const MrFOG4 = new Discord.Client();
const MrFOG5 = new Discord.Client();
const MrFOG6 = new Discord.Client();
const MrFOG7 = new Discord.Client();
const MrFOG8 = new Discord.Client();
const MrFOG9 = new Discord.Client();
const MrFOG10 = new Discord.Client();
const MrFOG11 = new Discord.Client();
const MrFOG12 = new Discord.Client();
const MrFOG13 = new Discord.Client();
const MrFOG14 = new Discord.Client();
const MrFOG15 = new Discord.Client();
const MrFOG16 = new Discord.Client();
const MrFOG17 = new Discord.Client();
const MrFOG18 = new Discord.Client();
const MrFOG19 = new Discord.Client();
const MrFOG20 = new Discord.Client();
const MrFOG21 = new Discord.Client();
const MrFOG22 = new Discord.Client();
const MrFOG23 = new Discord.Client();
const MrFOG24 = new Discord.Client();
const MrFOG25 = new Discord.Client();
const MrFOG26 = new Discord.Client();
const MrFOG27 = new Discord.Client();
const MrFOG28 = new Discord.Client();
const MrFOG29 = new Discord.Client();
const MrFOG30 = new Discord.Client();
const MrFOG31 = new Discord.Client();
const MrFOG32= new Discord.Client();
const MrFOG33 = new Discord.Client();
const MrFOG34 = new Discord.Client();
const MrFOG35= new Discord.Client();
const MrFOG36= new Discord.Client();
const MrFOG37= new Discord.Client();
const MrFOG38= new Discord.Client();
const MrFOG39= new Discord.Client();
const MrFOG40= new Discord.Client();
const MrFOG41= new Discord.Client();
const MrFOG42 = new Discord.Client();
const MrFOG43 = new Discord.Client();
const MrFOG44 = new Discord.Client();
const MrFOG45 = new Discord.Client();
const MrFOG46 = new Discord.Client();
const MrFOG47 = new Discord.Client();
const MrFOG48 = new Discord.Client();
const MrFOG49 = new Discord.Client();
const MrFOG50 = new Discord.Client();
const MrFOG51 = new Discord.Client();
const MrFOG52 = new Discord.Client();
const MrFOG53 = new Discord.Client();
const MrFOG54 = new Discord.Client();
const MrFOG55 = new Discord.Client();
const MrFOG56 = new Discord.Client();
const MrFOG57 = new Discord.Client();
const MrFOG58 = new Discord.Client();
const MrFOG59 = new Discord.Client();
const MrFOG60 = new Discord.Client();
const MrFOG61 = new Discord.Client();
const MrFOG62 = new Discord.Client();
const MrFOG63 = new Discord.Client();
const MrFOG64= new Discord.Client();
const MrFOG65 = new Discord.Client();
const MrFOG66= new Discord.Client();
const MrFOG67= new Discord.Client();
const MrFOG68= new Discord.Client();
const MrFOG69= new Discord.Client();
const MrFOG70= new Discord.Client();
const MrFOG71 = new Discord.Client();
const MrFOG72 = new Discord.Client()
const MrFOG73= new Discord.Client();
const MrFOG74 = new Discord.Client();
const MrFOG75 = new Discord.Client();
const MrFOG76 = new Discord.Client();
const MrFOG77 = new Discord.Client();
const MrFOG78 = new Discord.Client();
const MrFOG79 = new Discord.Client();
const MrFOG80 = new Discord.Client();
const MrFOG81 = new Discord.Client();
const MrFOG82 = new Discord.Client();
const MrFOG83 = new Discord.Client();
const MrFOG84 = new Discord.Client();
const MrFOG85 = new Discord.Client();
const MrFOG86 = new Discord.Client();
const MrFOG87 = new Discord.Client();
const MrFOG88 = new Discord.Client();
const MrFOG89 = new Discord.Client();
const MrFOG90 = new Discord.Client();
const MrFOG91 = new Discord.Client();
const MrFOG92 = new Discord.Client();
const MrFOG93 = new Discord.Client();
const MrFOG94 = new Discord.Client();
const MrFOG95 = new Discord.Client();
const MrFOG96= new Discord.Client();
const MrFOG97= new Discord.Client();
const MrFOG98= new Discord.Client();
const MrFOG99= new Discord.Client();
const MrFOG100= new Discord.Client();

MrFOG1.login("ODMwMTU4ODc5NDM4NTM2NzI1.YHCoTA.ilCOw_ourpkHVwzfSuT97uNbMGk");
MrFOG2.login("ODMwMTYwMTk2ODgxNzQzODgy.YHCpeA.Iu3Db8MWFe1AHq-iNEAuyCcoEZY");
MrFOG3.login("ODMwMTYxNjU3MjIwODI1MjA5.YHCqow.DsloP_TFmXPiDbrP_7NgONm-yKo");
MrFOG4.login("ODMwMTYyOTcwNDI3Nzg1Mjc3.YHCr7w.aFeoiW-jRz9gjBhWWWYVitMDEEo");
MrFOG5.login("ODMwMTY0Mjg0OTAxOTQ5NTQw.YHCu6g.JzO4MmpDLGBuwhw7TJI0NXQJ-OU");
MrFOG6.login("ODMwMTY3MzI0MDkwMDQwMzcx.YHCwHg.OIluThZpmG41uhlBgwrJ4ra65eI");
MrFOG7.login("");
MrFOG8.login("");
MrFOG9.login("");
MrFOG10.login("");
MrFOG11.login("");
MrFOG12.login("");
MrFOG13.login("");
MrFOG14.login("");
MrFOG15.login("");
MrFOG16.login("");
MrFOG17.login("");
MrFOG18.login("");
MrFOG19.login("");
MrFOG20.login("");
MrFOG21.login("");
MrFOG22.login("");
MrFOG23.login("");
MrFOG24.login("");
MrFOG25.login("");
MrFOG26.login("");
MrFOG27.login("");
MrFOG28.login("");
MrFOG29.login("");
MrFOG30.login("");
MrFOG31.login("");
MrFOG32.login("");
MrFOG33.login("");
MrFOG34.login("");
MrFOG35.login("");
MrFOG36.login("");
MrFOG37.login("");
MrFOG38.login("");
MrFOG39.login("");
MrFOG40.login("");
MrFOG41.login("");
MrFOG42.login("");
MrFOG43.login("");
MrFOG44.login("");
MrFOG45.login("");
MrFOG46.login("");
MrFOG47.login("");
MrFOG48.login("");
MrFOG49.login("");
MrFOG50.login("");
MrFOG51.login("");
MrFOG52.login("");
MrFOG53.login("");
MrFOG54.login("");
MrFOG55.login("");
MrFOG56.login("");
MrFOG57.login("");
MrFOG58.login("");
MrFOG59.login("");
MrFOG60.login("");
MrFOG61.login("");
MrFOG62.login("");
MrFOG63.login("");
MrFOG64.login("");
MrFOG65.login("");
MrFOG66.login("");
MrFOG67.login("");
MrFOG68.login("");
MrFOG69.login("");
MrFOG70.login("");
MrFOG71.login("");
MrFOG72.login("");
MrFOG73.login("");
MrFOG74.login("");
MrFOG75.login("");
MrFOG76.login("");
MrFOG77.login("");
MrFOG78.login("");
MrFOG79.login("");
MrFOG80.login("");
MrFOG81.login("");
MrFOG82.login("");
MrFOG83.login("");
MrFOG84.login("");
MrFOG85.login("");
MrFOG86.login("");
MrFOG87.login("");
MrFOG88.login("");
MrFOG89.login("");
MrFOG90.login("");
MrFOG91.login("");
MrFOG92.login("");
MrFOG93.login("");
MrFOG94.login("");
MrFOG95.login("");
MrFOG96.login("");
MrFOG97.login("");
MrFOG98.login("");
MrFOG99.login("");
MrFOG100.login("");
